### ISSUE TITLE
Build the devcontainer seperate, then use it as a container image for actions

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/devcontainers-contrib-features#4]
https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

Build the devcontainer when new changes on `path: .devcontainer`, then push that image to the `${{ github.repository }}-devcontainer` image, then pull that using

```yml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: node:14.16
```
